# Generated by Django 4.2.3 on 2024-09-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_notes_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="learningnote",
            new_name="learning_no_user_id_3bff8f_idx",
            old_name="learning_no_user_id_c272da_idx",
        ),
        migrations.AlterModelTable(name="learningnote", table="learning_note",),
    ]
