# Generated by Django 4.2.3 on 2024-09-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning_notes_app",
            "0002_rename_learning_no_user_id_c272da_idx_learning_no_user_id_3bff8f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(name="label", table="label",),
    ]
