# Generated by Django 4.2.3 on 2024-11-11 12:42

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learning_notes_app", "0004_collection_learningnote_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningnote",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name="learningnote",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collection_notes",
                to="learning_notes_app.collection",
            ),
        ),
        migrations.AddIndex(
            model_name="learningnote",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="learning_no_search__6981de_gin"
            ),
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER learningnote_search_vector_update
            BEFORE INSERT OR UPDATE ON learning_note
            FOR EACH ROW EXECUTE FUNCTION
            tsvector_update_trigger(search_vector, 'pg_catalog.english', title, content);
            """
        ),
    ]
