# Generated by Django 4.2.3 on 2024-11-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_notes_app", "0006_populate_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningnote",
            name="generated_questions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
